# Generated by Django 4.0.2 on 2022-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamentos',
            name='dose',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='frequencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='rh',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='setor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tratamentos',
            name='unidade',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='tratamentos',
            name='duracao',
            field=models.IntegerField(null=True),
        ),
    ]
